<footer class="footer">
		<div class="inner-footer">
			<div class="row nav-bottom">
				<div class="col-sm-8">
					<div class="col-sm-5">
						<h3>About</h3>
						<!-- 					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas in libero eget orci aliquet ultrices in at risus. In hendrerit rutrum sem, vel posuere orci varius a. Nulla rhoncus odio quis convallis gravida.</p>
 							-->
						<div class="social">
							<a href="" class="facebook"><i class="fa fa-facebook"></i></a>
							<a href="" class="twitter"><i class="fa fa-twitter"></i></a>
							<a href="" class="google"><i class="fa fa-google"></i></a>

						</div>
						<h4><a href="tel">Rufen Sie uns an</a> <br />Email : olaruphone@gmx.de</h4>
					</div>
					<div class="col-sm-4">
						<h3>Kundenbewertungen</h3>
						<ul class="nav-list">
							<li class="media">
								<a href="" class="pull-left"><img width="75" src="/public/assets/img/iphone6-select-2014.jpg" alt="" /></a>
								<div class="media-body">
									<h5><a href="">Dachte nie, dass jemand bei mir meine Handy so schnell Repariert</a></h5>
									<i>18 Jul 2021</i>
								</div>
							</li>
							<li class="media">
								<a href="" class="pull-left"><img width="75" src="/public/assets/img/iphone6-select-2014.jpg" alt="" /></a>
								<div class="media-body">
									<h5><a href="">Schnell und unkopliziert</a></h5>
									<i>18 Jul 2021</i>
								</div>
							</li>
							<li class="media">
								<a href="" class="pull-left"><img width="75" src="/public/assets/img/iphone6-select-2014.jpg" alt="" /></a>
								<div class="media-body">
									<h5><a href="">Immer gerne wieder</a></h5>
									<i>18 Jul 2021</i>
								</div>
							</li>
						</ul>
					</div>
					<div class="col-sm-3">
						<h3>Über uns</h3>
						<ul class="nav-list">
							<li><a href="">Kotakt</a></li>
							<li><a href="">FAQ</a></li>
							<li><a href="">Datenschutz</a></li>
							<li><a href="">AGB</a></li>
							<li><a href="">Reparaturablauf</a></li>
							<li><a href="">Wiederruf</a></li>
						</ul>
					</div>
				</div>
				<!-- <div class="col-sm-4">
			<iframe height="240" style="width: 100%; border: 0;" src="//www.facebook.com/plugins/likebox.php?href=http%3A%2F%2Fwww.facebook.com%2Fcrtvmrkt&amp;colorscheme=dark&amp;show_faces=true&amp;header=false&amp;stream=false&amp;show_border=false"></iframe>
			</div> -->
			</div>
			<hr />
			<div class="copyright">
				<div class="col-sm-6">
					<span>&copy; Copyright 2021 Claudiu Olaru All right reserved</span>
				</div>
				<div class="col-sm-6 text-right">
					<div class="pull-right">
						<p>Newsletter :</p>
						<form class="form-inline" id="validate-form" method="post" action="#" enctype="multipart/form-data">
							<div class="form-group">
								<input type="email" name="email" placeholder="--- Enter email address ---" class="form-control required">
							</div>
							<button class="btn btn-primary" type="submit">Anmelden</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</footer>