<header class="header">
	<div class="inner-header">
		<div class="logo">
			<h4>Handyreparatur vor Ort</h4>
			<!-- <a href="index.php"><img src="/public/assets/img/logo@3x.png" alt="abc point" /></a> -->
			<!--<div class="cc">
				<span><i class="fa fa-phone"></i> +66 2 123 4567</span>
			</div>-->
		</div>
		<div class="searchbar">
			<div class="search-toggle">
				<i class="fa fa-search icon-search"></i>
				<i class="fa fa-remove icon-remove"></i>
			</div>
			<div class="search">
				<input type="text" placeholder="Search Product zB, Batterie" class="search-box" /><!-- fix inline-block --><button class="search-btn"><i class="fa fa-search"></i></button>
			</div>			
			<!-- <a href="wishlist.php" class="wishlist"><i class="fa fa-heart"></i> <b>21</b></a> -->
			<a href=".checkout" data-toggle="modal" class="basket"><i class="fa fa-shopping-cart"></i> <b>$ 12,000</b> <span>4</span></a>
		</div>
		<!--<div class="section-button">
			<a href="" class="active">Online Service <i class="fa fa-angle-down"></i></a>
			<a href="">Corporate  <i class="fa fa-angle-right"></i></a>
		</div>-->
	</div>
</header>