<div class="section">
	<h2>Blitzreparatur</h2>
	<div class="row list-thumbnail inequitable">
		<div class="col-xs-12 col-sm-5 col-md-4 first">
			<div class="thumbnail">
				<a href="">
					<img src="/public/assets/img/products/9.jpg" alt="" />
				</a>
				<div class="caption">
					<h3>Samsung Galaxy S5</h3>
					<p>Akkutausch innen in eine Stunde für unglaubliche preis und Zeit</p>
					<h5 class="price">$49.99€<span class="strike">79,99€</span></h5>
					<a href="" class="like active"><i class="fa fa-heart"></i> 40</a>
				</div>
			</div>
		</div>
		<div class="col-xs-12 col-sm-7 col-md-8">
			<div class="col-xs-6 col-sm-4 col-md-3">
				<div class="thumbnail">
					<a href="product-detail.php">
						<span class="label-save">Rabatt <i>%</i></span>
						<img src="/public/assets/img/products/5.jpg" alt="" />
						<img class="hover" src="/public/assets/img/products/5-5.jpg" alt="" />
					</a>
					<div class="caption">
						<h3>Samsung S10 Hörbuchse Reparatur</h3>
						<h5 class="price">39,99€<span class="strike">79,00€</span></h5>
						<a href="" class="like active"><i class="fa fa-heart"></i> 0</a>
					</div>
				</div>
			</div>
			<div class="col-xs-6 col-sm-4 col-md-3">
				<div class="thumbnail">
					<a href="product-detail.php">
						<img src="/public/assets/img/products/11.jpg" alt="" />
						<img class="hover" src="/public/assets/img/products/11-11.jpg" alt="" />
					</a>
					<div class="caption">
						<h3>DELL Display-tausch im Ort</h3>
						<h5 class="price">199,00€<span class="strike">399,00€</span></h5>
						<a href="" class="like"><i class="fa fa-heart"></i> 37</a>
					</div>
				</div>
			</div>
			<div class="col-xs-6 col-sm-4 col-md-3">
				<div class="thumbnail">
					<a href="product-detail.php">
						<!-- 	<img src="/public/assets/img/products/11.jpg" alt="" />
									<img class="hover" src="/public/assets/img/products/11-11.jpg" alt="" /> -->
					</a>
					<div class="caption">
						<h3> </h3>
						<!-- 									<h5 class="price">199,00€<span class="strike">399,00€</span></h5>
 									--> <a href="" class="like"><i class="fa fa-heart"></i> 37</a>
					</div>
				</div>
			</div>
			<!-- <div class="col-xs-6 col-sm-4 col-md-3">
							<div class="thumbnail">
								<span class="label-save">Save <i>5%</i></span>
								<a href="product-detail.php">
									<img src="/public/assets/img/products/12.jpg" alt="" />
								</a>
								<div class="caption">
									<h3>Nikon D5200 Digital Camera</h3>
									<h5 class="price">$9,500.00<span class="strike">$9,000.00</span></h5>
									<a href="" class="like"><i class="fa fa-heart"></i> 133</a>
								</div>
					        </div>
						</div> -->
			<div class="col-xs-6 col-sm-4 col-md-3">
				<div class="thumbnail">
					<a href="product-detail.php">
						<img src="/public/assets/img/products/7.jpg" alt="" />
					</a>
					<div class="caption">
						<h3>21.5-inch iMac 2.9GHz Processor 1 TB Storage</h3>
						<h5 class="price">1,499.00€</h5>
						<a href="" class="like active"><i class="fa fa-heart"></i> 6</a>
					</div>
				</div>
			</div>
			<div class="col-xs-6 col-sm-4 col-md-3">
				<div class="thumbnail">
					<a href="product-detail.php">
						<span class="label-save">Rabatt <i>3%</i></span>
						<img src="/public/assets/img/products/8.jpg" alt="" />
						<img class="hover" src="/public/assets/img/products/8-8.jpg" alt="" />
					</a>
					<div class="caption">
						<h3>Xperia™ Tablet S (16GB)</h3>
						<h5 class="price">319€<span class="strike">380€</span></h5>
						<a href="" class="like active"><i class="fa fa-heart"></i> 32</a>
					</div>
				</div>
			</div>
			<div class="col-xs-6 col-sm-4 col-md-3">
				<div class="thumbnail">
					<a href="product-detail.php">
						<img src="/public/assets/img/products/1.jpg" alt="" />
						<img class="hover" src="/public/assets/img/products/1-1.jpg" alt="" />
					</a>
					<div class="caption">
						<h3>iPhone 6 Display-tausch</h3>
						<h5 class="price">49€</h5>
						<a href="" class="like active"><i class="fa fa-heart"></i> 12</a>
					</div>
				</div>
			</div>
			<div class="col-xs-6 col-sm-4 col-md-3 hidden-sm">
				<div class="thumbnail">
					<a href="product-detail.php">
						<span class="label-save">Save <i>5%</i></span>
						<img src="/public/assets/img/products/2.jpg" alt="" />
					</a>
					<div class="caption">
						<h3>HTC Desire 820 Akku</h3>
						<h5 class="price">49€</h5>
						<a href="" class="like active"><i class="fa fa-heart"></i> 2</a>
					</div>
				</div>
			</div>
			<div class="col-xs-6 col-sm-4 col-md-3 hidden-sm">
				<div class="thumbnail">
					<a href="product-detail.php">
						<span class="label-save">Save <i>7%</i></span>
						<img src="/public/assets/img/products/4.jpg" alt="" />
					</a>
					<div class="caption">
						<h3>LG Nexus 5 Power Button</h3>
						<h5 class="price">19.00€<span class="strike">49.00€</span></h5>
						<a href="" class="like active"><i class="fa fa-heart"></i> 7</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>