<div class="row section">
				<h2>Wochenangebot</h2>
				<div class="list-thumbnail list-slide">
					<div class="col-sm-12">
						<div class="thumbnail">
							<a href="product-detail.php">
								<img src="./public/assets/img/products/1.jpg" alt="" />
								<img class="hover" src="/public/assets/img/products/1-1.jpg" alt="" />
							</a>
							<div class="caption">
								<h3>iPhone 6 Reparaturen bis zum 20% Rabatt</h3>
								<h5 class="price">20% Rabatt</h5>
								<a href="" class="like"><i class="fa fa-heart"></i> 12</a>
							</div>
				        </div>
					</div>
					<div class="col-sm-12">
						<div class="thumbnail">
							<a href="product-detail.php">
								<span class="label-save">Rabatt <i>%</i></span>
								<img src="/public/assets/img/products/2.jpg" alt="" />
							</a>
							<div class="caption">
								<h3>Kostenlose Fehlerdiagnose für jede HTC Gerät </h3>
								<h5 class="price">0€<span class="strike">25€</span></h5>
								<a href="" class="like"><i class="fa fa-heart"></i> 2</a>
							</div>
				        </div>
					</div>
					<div class="col-sm-12">
						<div class="thumbnail">
							<a href="product-detail.php">
								<img src="/public/assets/img/products/3.jpg" alt="" />
							</a>
							<div class="caption">
								<h3>MacBook Air Temperaturpaste Angebot</h3>
								<h5 class="price">65€</h5>
								<a href="" class="like"><i class="fa fa-heart"></i> 30</a>
							</div>
				        </div>
					</div>
					<div class="col-sm-12">
						<div class="thumbnail">
							<a href="product-detail.php">
							<span class="label-save">Rabatt <i>%</i></span>
								<img src="/public/assets/img/products/4.jpg" alt="" />
							</a>
							<div class="caption">
								<h3>LG Nexus 5</h3>
								<h5 class="price">$319.00<span class="strike">$349.00</span></h5>
								<a href="" class="like active"><i class="fa fa-heart"></i> 7</a>
							</div>
				        </div>
					</div>
					<div class="col-sm-12">
						<div class="thumbnail">
							<a href="product-detail.php">
							<span class="label-save">Rabatt <i>%</i></span>
								<img src="/public/assets/img/products/5.jpg" alt="" />
								<img class="hover" src="/public/assets/img/products/5-5.jpg" alt="" />
							</a>
							<div class="caption">
								<h3>Sony Black Edition (Red/Black)</h3>
								<h5 class="price">90.00€<span class="strike">105.00€</span></h5>
								<a href="" class="like active"><i class="fa fa-heart"></i> 0</a>
							</div>
				        </div>
					</div>
					<div class="col-sm-12">
						<div class="thumbnail">
							<a href="product-detail.php">
							<span class="label-save">Rabatt <i>%</i></span>
								<img src="/public/assets/img/products/6.jpg" alt="" />
							</a>
							<div class="caption">
								<h3>32-inch Toshiba LED TV (32L3450VT)</h3>
								<h5 class="price">250€<span class="strike">300€</span></h5>
								<a href="" class="like active"><i class="fa fa-heart"></i> 114</a>
							</div>
				        </div>
					</div>
					<div class="col-sm-12">
						<div class="thumbnail">
							<a href="product-detail.php">
								<img src="/public/assets/img/products/7.jpg" alt="" />
							</a>
							<div class="caption">
								<h3>21.5-inch iMac 2.9GHz Processor 1 TB Storage</h3>
								<h5 class="price">$1,499.00</h5>
								<a href="" class="like active"><i class="fa fa-heart"></i> 6</a>
							</div>
				        </div>
					</div>
					<div class="col-sm-12">
						<div class="thumbnail">
							<a href="product-detail.php">
							<span class="label-save">Rabatt <i>%</i></span>
								<img src="/public/assets/img/products/8.jpg" alt="" />
								<img class="hover" src="/public/assets/img/products/8-8.jpg" alt="" />
							</a>
							<div class="caption">
								<h3>Xperia™ Tablet S (16GB)</h3>
								<h5 class="price">$399<span class="strike">$380</span></h5>
								<a href="" class="like active"><i class="fa fa-heart"></i> 32</a>
							</div>
				        </div>
					</div>
				</div>		
			</div>