<div class="container main">
    <div class="row section">
        <h2>Wochenangebot</h2>
        <div class="list-thumbnail list-slide">
            <?php foreach ($params['herstellers'] as $key) : ?>
                <?php if (isset($key['name'])) : ?>
                    <div class="col-sm-12">
                        <div class="thumbnail">
                            <a href="/?type=<?= $key['id'] ?>" class="">
                                <?= isset($key['logo']) ? $key['logo'] : $key['type'] ?>
                                <img class="hover" src="/public/assets/img/products/1-1.jpg" alt="" />

                                <div class="caption">
                                    <h3>iPhone 6 Reparaturen bis zum 20% Rabatt</h3>
                                    <h5 class="price">20% Rabatt</h5>
                            </a>
                        </div>
                    </div>
        </div>
    <?php elseif (isset($key['preis'])) : ?>
        <div class="col-sm-12">
            <div class="thumbnail">
                <a href="/?auftrag=<?= $key['type'] ?>">
                    <img src="./public/assets/img/products/1.jpg" alt="" />
                    <img class="hover" src="/public/assets/img/products/1-1.jpg" alt="" />

                    <div class="caption">
                        <h3><?= isset($key['logo']) ? $key['logo'] : $key['type'] ?></h3>
                        <h4><?= $key['reparaturArt'] ?></h4>
                        <h5> für <?= $key['preis'] ?>€</h5><br>
                        <p>Artikel-Nr.:<?= $key['preiseID'] ?></p>
                        <h5 class="price">20% Rabatt</h5>
                </a>
            </div>
        </div>
    </div>


<?php else : ?>
    <div class="col-sm-12">
        <div class="thumbnail">
            <a href="/?preise=<?= $key['type'] ?>" class="">
                <img src="./public/assets/img/products/1.jpg" alt="" />
                <!--       <?= isset($key['logo']) ? $key['logo'] : $key['type'] ?> -->
                <img class="hover" src="/public/assets/img/products/1-1.jpg" alt="" />

                <div class="caption">
                    <h3> <?= isset($key['logo']) ? $key['logo'] : $key['type'] ?></h3>
                    <h5 class="price">20% Rabatt</h5>
            </a>
        </div>
    </div>
</div>

<?php endif; ?>
<?php endforeach; ?>
</div>
</div>
</div>