<div class="modal checkout fade">
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
				<h4 class="modal-title">Your Order</h4>
			</div>
			<div class="modal-body">
				<form class="form-horizontal">
					<table class="table table-striped">
						<thead>
							<tr>
								<th>Product Detail</th>
								<th class="text-right" style="width: 90px;">Order</th>
								<th class="text-right" style="width: 80px;">Amount</th>
								<th style="width: 20px;"></th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td><img src="/public/assets/img/products/1.jpg" style="width: 50px;" class="pull-left hidden-xs" alt="" /> Samsung Galaxy S5
								</td>
								<td class="text-right">
									<div class="quantity">
									    <div class="minus">
									    	<a class="ddd" href="#">-</a>
									    </div>
									    <div class="input">
									        <input type="text" class="quntity-input" value="1" />
									    </div>
									    	<div class="plus"> <a class="ddd" href="#">+</a>
									    </div>
									</div>
								</td>
								<td class="text-right">$2,000</td>
								<td class="text-right">
									<a href=""><i class="fa fa-trash-o red"></i></a>
								</td>
							</tr>
							<tr>
								<td class="text-right" colspan="2"><b>Total Amount</b></td>
								<td class="text-right">$2,000</td>
								<td class="text-right"></td>
							</tr>
						</tbody>
				    </table>
					
				</form>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Continue Shopping</button>
				<a href="checkout.php" class="btn btn-primary">Checkout</a>
			</div>
	    </div>
	</div>
</div>