<div class="nav-top blue">
	<div class="userbar">
		<div class="contact">
			<a href="" class="tel"><i class="fa fa-phone"></i>Telefonnummer</a>
			<span class="split"></span>
			<a href="" class="email"><i class="fa fa-envelope-o"></i> and email </a>
		</div>
		<div class="lang">
			<a href="" id="lang" class="dropdown-toggle" data-toggle="dropdown">Techniker <span class="caret"></span></a>
			<ul class="dropdown-menu" aria-labelledby="lang">
				<li><a href="" >Deutsch</a></li>
				<li><a href="" >Eng</a></li>
			</ul>
		</div>
		<span class="split"></span>
		<!-- Before Login -->
		<a href="login.php">Login</a> <span>or</span> <a href="login.php">Register</a>
		<!-- End Before Login -->
		<!-- after Login -->
				<!-- End after Login -->
	</div>
</div>