<div class="container  section">
	<h2>New Arrivals</h2>
	<ul class="nav nav-tabs nav-button">
		<li class="active">
			<a data-toggle="tab" href="#computer">Computer</a>
		</li>
		<li>
			<a data-toggle="tab" href="#smartphone">Smart Phone</a>
		</li>
		<li>
			<a data-toggle="tab" href="#camera">Camera</a>
		</li>
		<li>
			<a data-toggle="tab" href="#sport">Sport</a>
		</li>
	</ul>
	<div class="tab-content">
		<div id="computer" class="tab-pane fade in active">
			<div class="row list-thumbnail list-slide">
				<div class="col-sm-12">
					<div class="thumbnail">
						<a href="product-detail.php">
							<img src="/public/assets/img/products/7.jpg" alt="" />
						</a>
						<div class="caption">
							<h3>21.5-inch iMac 2.9GHz Processor 1 TB Storage</h3>
							<h5 class="price">$1,499.00</h5>
							<a href="" class="like active"><i class="fa fa-heart"></i> 6</a>
						</div>
					</div>
				</div>
				<div class="col-sm-12">
					<div class="thumbnail">
						<a href="product-detail.php">
							<img src="/public/assets/img/products/11.jpg" alt="" />
							<img class="hover" src="/public/assets/img/products/11-11.jpg" alt="" />
						</a>
						<div class="caption">
							<h3>DELL Ultrabook XPS L321X</h3>
							<h5 class="price">$1,460.00</h5>
							<a href="" class="like"><i class="fa fa-heart"></i> 104</a>
						</div>
					</div>
				</div>
				<div class="col-sm-12">
					<div class="thumbnail">
						<a href="product-detail.php">
							<span class="label-save">Save <i>15%</i></span>
							<img src="/public/assets/img/products/6.jpg" alt="" />
						</a>
						<div class="caption">
							<h3>32-inch Toshiba LED TV (32L3450VT)</h3>
							<h5 class="price">$300.00<span class="strike">$250.00</span></h5>
							<a href="" class="like active"><i class="fa fa-heart"></i> 114</a>
						</div>
					</div>
				</div>
				<div class="col-sm-12">
					<div class="thumbnail">
						<a href="product-detail.php">
							<img src="/public/assets/img/products/7.jpg" alt="" />
						</a>
						<div class="caption">
							<h3>21.5-inch iMac 2.9GHz Processor 1 TB Storage</h3>
							<h5 class="price">$1,499.00</h5>
							<a href="" class="like active"><i class="fa fa-heart"></i> 6</a>
						</div>
					</div>
				</div>
				<div class="col-sm-12">
					<div class="thumbnail">
						<a href="product-detail.php">
							<img src="/public/assets/img/products/11.jpg" alt="" />
							<img class="hover" src="/public/assets/img/products/11-11.jpg" alt="" />
						</a>
						<div class="caption">
							<h3>DELL Ultrabook XPS L321X</h3>
							<h5 class="price">$1,460.00</h5>
							<a href="" class="like"><i class="fa fa-heart"></i> 104</a>
						</div>
					</div>
				</div>
				<div class="col-sm-12">
					<div class="thumbnail">
						<a href="product-detail.php">
							<span class="label-save">Save <i>15%</i></span>
							<img src="/public/assets/img/products/6.jpg" alt="" />
						</a>
						<div class="caption">
							<h3>32-inch Toshiba LED TV (32L3450VT)</h3>
							<h5 class="price">$300.00<span class="strike">$250.00</span></h5>
							<a href="" class="like active"><i class="fa fa-heart"></i> 114</a>
						</div>
					</div>
				</div>
				<div class="col-sm-12">
					<div class="thumbnail">
						<a href="product-detail.php">
							<span class="label-save">Save <i>15%</i></span>
							<img src="/public/assets/img/products/7.jpg" alt="" />
						</a>
						<div class="caption">
							<h3>21.5-inch iMac 2.9GHz Processor 1 TB Storage</h3>
							<h5 class="price">$1,499.00</h5>
							<a href="" class="like active"><i class="fa fa-heart"></i> 6</a>
						</div>
					</div>
				</div>
				<div class="col-sm-12">
					<div class="thumbnail">
						<a href="product-detail.php">
							<span class="label-save">Save <i>15%</i></span>
							<img src="/public/assets/img/products/11.jpg" alt="" />
						</a>
						<div class="caption">
							<h3>DELL Ultrabook XPS L321X</h3>
							<h5 class="price">$1,460.00</h5>
							<a href="" class="like"><i class="fa fa-heart"></i> 104</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div id="smartphone" class="tab-pane fade">
			<div class="list-thumbnail list-slide">
				<div class="col-sm-12">
					<div class="thumbnail">
						<a href="product-detail.php">
							<span class="label-save">Save <i>5%</i></span>
							<img src="/public/assets/img/products/2.jpg" alt="" />
						</a>
						<div class="caption">
							<h3>HTC Desire 820 Gray-Blue</h3>
							<h5 class="price">$95.00<span class="strike">$100.00</span></h5>
							<a href="" class="like active"><i class="fa fa-heart"></i> 2</a>
						</div>
					</div>
				</div>
				<div class="col-sm-12">
					<div class="thumbnail">
						<a href="product-detail.php">
							<span class="label-save">Save <i>7%</i></span>
							<img src="/public/assets/img/products/4.jpg" alt="" />
						</a>
						<div class="caption">
							<h3>LG Nexus 5</h3>
							<h5 class="price">$319.00<span class="strike">$349.00</span></h5>
							<a href="" class="like active"><i class="fa fa-heart"></i> 7</a>
						</div>
					</div>
				</div>
				<div class="col-sm-12">
					<div class="thumbnail">
						<a href="product-detail.php">
							<span class="label-save">Save <i>3%</i></span>
							<img src="/public/assets/img/products/8.jpg" alt="" />
							<img class="hover" src="/public/assets/img/products/8-8.jpg" alt="" />
						</a>
						<div class="caption">
							<h3>Xperia™ Tablet S (16GB)</h3>
							<h5 class="price">$399.00<span class="strike">$380.00</span></h5>
							<a href="" class="like active"><i class="fa fa-heart"></i> 32</a>
						</div>
					</div>
				</div>
				<div class="col-sm-12">
					<div class="thumbnail">
						<a href="product-detail.php">
							<img src="/public/assets/img/products/1.jpg" alt="" />
							<img class="hover" src="/public/assets/img/products/1-1.jpg" alt="" />
						</a>
						<div class="caption">
							<h3>iPhone 6 (16GB Space Grey, Silver)</h3>
							<h5 class="price">$200.00</h5>
							<a href="" class="like active"><i class="fa fa-heart"></i> 12</a>
						</div>
					</div>
				</div>
				<div class="col-sm-12">
					<div class="thumbnail">
						<a href="product-detail.php">
							<span class="label-save">Save <i>5%</i></span>
							<img src="/public/assets/img/products/2.jpg" alt="" />
						</a>
						<div class="caption">
							<h3>HTC Desire 820 Gray-Blue</h3>
							<h5 class="price">$95.00<span class="strike">$100.00</span></h5>
							<a href="" class="like active"><i class="fa fa-heart"></i> 2</a>
						</div>
					</div>
				</div>
				<div class="col-sm-12">
					<div class="thumbnail">
						<a href="product-detail.php">
							<span class="label-save">Save <i>7%</i></span>
							<img src="/public/assets/img/products/4.jpg" alt="" />
						</a>
						<div class="caption">
							<h3>LG Nexus 5</h3>
							<h5 class="price">$319.00<span class="strike">$349.00</span></h5>
							<a href="" class="like active"><i class="fa fa-heart"></i> 7</a>
						</div>
					</div>
				</div>
				<div class="col-sm-12">
					<div class="thumbnail">
						<a href="product-detail.php">
							<span class="label-save">Save <i>3%</i></span>
							<img src="/public/assets/img/products/8.jpg" alt="" />
							<img class="hover" src="/public/assets/img/products/8-8.jpg" alt="" />
						</a>
						<div class="caption">
							<h3>Xperia™ Tablet S (16GB)</h3>
							<h5 class="price">$399.00<span class="strike">$380.00</span></h5>
							<a href="" class="like active"><i class="fa fa-heart"></i> 32</a>
						</div>
					</div>
				</div>
				<div class="col-sm-12">
					<div class="thumbnail">
						<a href="product-detail.php">
							<img src="/public/assets/img/products/1.jpg" alt="" />
							<img class="hover" src="/public/assets/img/products/1-1.jpg" alt="" />
						</a>
						<div class="caption">
							<h3>iPhone 6 (16GB Space Grey, Silver)</h3>
							<h5 class="price">$200.00</h5>
							<a href="" class="like active"><i class="fa fa-heart"></i> 12</a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div id="camera" class="tab-pane fade"></div>
		<div id="sport" class="tab-pane fade"></div>
	</div>

</div>