<div class="slide-product text-center">
	<div class="row">
		<div class="col-sm-8">
			<a href="#1">
				<img src="public/assets/img/banner1.jpg" alt="" />
			</a>
		</div>
		<div class="col-sm-4">
			<div class="row">
				<div class="col-xs-6 col-sm-12">
					<a href="#2">
						<img src="public/assets/img/banner3.jpg" alt="" />
					</a>
				</div>
				<div class="col-xs-6 col-sm-12">
					<a href="#3">
						<img src="public/assets/img/banner2.jpg" alt="" />
					</a>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-sm-8">
			<a href="#2">
				<img src="/public/assets/img/banner3.jpg" alt="" />
			</a>
		</div>
		<div class="col-sm-4">
			<div class="row">
				<div class="col-xs-6 col-sm-12">
					<a href="#3">
						<img src="/public/assets/img/banner2.jpg" alt="" />
					</a>
				</div>
				<div class="col-xs-6 col-sm-12">
					<a href="#1">
						<img src="/public/assets/img/banner1.jpg" alt="" />
					</a>
				</div>
			</div>
		</div>
	</div>
</div>
<ul class="option-list">
	<li>
		<a href="">
			<i class="fa fa-truck"></i>
			<!-- fix inline-block
				-->
			<div class="option-text">
				<h3>Reaparatur im Ort</h3>
				<h4>Unserer Techniker kommen gerne vorbei</h4>
			</div>
		</a>
	</li>
	<li>
		<a href="">
			<i class="fa fa-retweet"></i>
			<!-- fix inline-block
				-->
			<div class="option-text">
				<h3>Garantie</h3>
				<h4>Preis und Leistunggarantie</h4>
			</div>
		</a>
	</li>
	<li>
		<a href="">
			<i class="fa fa-gift"></i>
			<!-- fix inline-block
				-->
			<div class="option-text">
				<h3>Angeboten</h3>
				<h4>% Immer neue Angeboten %</h4>
			</div>
		</a>
	</li>
</ul>
