<!DOCTYPE html>
<html>

<head>
	<title>CheckmyPhone</title>
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="viewport" content="user-scalable=0,initial-scale=1.0, maximum-scale=1, minimum-scale=1" />
	<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css" />
	<link href="/public/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<!-- 	<link href="http://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css" rel="stylesheet" />	
 -->	<link href="/public/assets/css/font.css" rel="stylesheet" type="text/css" />
	<link href="/public/assets/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
	<link href="/public/assets/css/font-custom.css" rel="stylesheet" type="text/css" />
	<link href="/public/assets/css/owl.carousel.css" rel="stylesheet">
	<link href="/public/assets/css/overwrite-bootstrap.css" rel="stylesheet" type="text/css" />
	<link href="/public/assets/css/custom.css" rel="stylesheet" type="text/css" />
	<link href="/public/assets/css/color-switch.css" rel="stylesheet" type="text/css" />
	<link href="#green" id="color" rel="stylesheet" type="text/css" /> 
	<!-- ----------script------------->
	<script type="text/javascript" src="/public/assets/js/jquery.js"></script>
	<script type="text/javascript" src="/public/assets/js/color-switch.js"></script>
	<script type="text/javascript" src="http://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
	<script type="text/javascript" src="/public/assets/js/jquery.ui.touch-punch.min.js"></script>
	<script type="text/javascript" src="/public/assets/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="/public/assets/js/holder.js"></script>
	<script type="text/javascript" src="/public/assets/js/jquery.validate.min.js"></script>
	<script type="text/javascript" src="/public/assets/js/jquery.dotdotdot.min.js"></script>
	<script type="text/javascript" src="/public/assets/js/jquery.elevateZoom.min.js"></script>
	<script type="text/javascript" src="/public/assets/js/jquery.zoom.min.js"></script>
	<script type="text/javascript" src="/public/assets/js/owl.carousel.min.js"></script>
	<script type="text/javascript" src="/public/assets/js/custom.js"></script>
</head>

<body>
	<div class="wrapper">

		 <div class="color-switch">
			<ul>
				<li><a id="brown" class="brown change" href="#brown"><i class="fa fa-check"></i></a></li>
				<li><a id="red" class="red change" href="#red"><i class="fa fa-check"></i></a></li>
				<li><a id="yellow" class="yellow change" href="#yellow"><i class="fa fa-check"></i></a></li>
				<li><a id="blue" class="blue change" href="#blue"><i class="fa fa-check"></i></a></li>
				<li><a id="green" class="green change" href="#green"><i class="fa fa-check"></i></a></li>
				<li><a id="gray" class="gray change" href="#gray"><i class="fa fa-check"></i></a></li>
				<li><a id="modernstyle" class="modernstyle change" href="#modernstyle"><i class="fa fa-check"></i></a></li>
			</ul>
			<i class="fa fa-paint-brush"></i>
		</div> 

		<?php foreach ($params as $key => $value) {
			echo ($value);
		}
		?>

		<!-- NavTop hier mit PHP-->

		<!-- header mit PHP-->

		<!-- navMain mit PHP-->

		<!-- Modal Checkout mit PHP-->

		<!-- /.modal-content mit PHP-->

		<!-- Modal mit PHP-->

	</div>
	<!-- maicontainer mit PHP-->


	<!-- footer mit PHP-->
</body>

</html>